### ISSUE TITLE
0.1 Milestones (due Friday)

### ISSUE THREAD

**Issue by jmulford-bw** [Bandwidth/numbers-java-sdk#3]
All tasks should have proper documentation (in the Readme would be great)

Docs for these endpoints can be found here: https://dev.bandwidth.com/v2-messaging/concepts/numberOrderingSummary.html

- [ ] Search phone numbers, receive response
- [ ] Order phone numbers, receive response
- [ ] Get order information, receive response
- [ ] Disconnect phone number, receive response
- [ ] Get disconnect information, receive response
